### ISSUE TITLE
Running on a GPU

### ISSUE THREAD

**Issue by chokosabe** [christianhidber/easyagents#111]
It isn't clear whether this can run using a gpu. Tried with the tf-nightly-gpu build and I'm getting an error. 

It isn't clear whether its the library or tensorflow itself. The environment is colab.

The error itself is detailed here:

https://github.com/tensorflow/tensorflow/issues/40385

**Comment by christianhidber** [comment]
Seems to be somewhere between TF and TF probability. EasyAgents is sitting on top of TF-agents, which in turn sits on TF. So I guess our chances are small to help from the EasyAgets side. Or do you have an suggestions ? In any case, we will try to update the direct dependencies of EasyAgents the next few weeks. So maybe that might then also have a "beneficial" impact.

**Comment by DJCordhose** [comment]
I know for sure that using tf agents installed by easyagents as a
dependency runs on GPU if there is one. Wouldn't be able to think of any
reason why easyagents itself should interfere.

**Comment by chokosabe** [comment]
Yeah this is looking more and more like a Tensorflow issue. Tried in Rllib and getting the same thing.
