### ISSUE TITLE
 max value of the episode rewards in the orso book training visualization always >= 0

### ISSUE THREAD

**Issue by christianhidber** [christianhidber/easyagents#29]
The max value of the episode rewards in the orso book training visualization seems always to be >= 0. Is this correct ?

![image](https://user-images.githubusercontent.com/51879047/63216602-f6d49600-c137-11e9-846a-1c58d95b1358.png)

**Comment by DJCordhose** [comment]
Yes, strangely enough it does not train at all anymore. Also number of steps per episode are stuck at 50. Orso oscillate between two states. Environment has not changed and PPO still works with Line world. Weird, no idea what is going on.

**Comment by DJCordhose** [comment]
it seems we are just too impatient, when you wait for a few thousand episodes, reward indeed becomes positive and steps go under 20, just as expected.

**Comment by DJCordhose** [comment]
![download](https://user-images.githubusercontent.com/394409/63428613-3e993d00-c418-11e9-9fa0-e949215acf21.png)

**Comment by christianhidber** [comment]
That's right. I was more concerned about the start:
![image](https://user-images.githubusercontent.com/51879047/63428907-f9c1d600-c418-11e9-9cb6-983ba5446d81.png)
It feels quite unlikely, that in the evaluations at episodes 0, 50 and 100 we always reach a maximum of 0 (the min and average look ok). Consistently. I would expect that at some point we should have a maximum < 0.

**Comment by DJCordhose** [comment]
Ah, now I understand. This looks fishy, indeed.

**Comment by christianhidber** [comment]
solved in v1
