### ISSUE TITLE
Add a score method to an agent

### ISSUE THREAD

**Issue by DJCordhose** [christianhidber/easyagents#47]
like 'play' should play a number of episodes and output the total rewards for them. Maybe also give min, max, mean, and std.

**Comment by christianhidber** [comment]
We already support:
![image](https://user-images.githubusercontent.com/51879047/65370873-f27f2980-dc5d-11e9-9bf9-aa117b61c9ea.png)

Would that be similar, but having an additional min/max area ?

**Comment by DJCordhose** [comment]
I was rather thinking of something like the score method in sklearn or evaluate in Keras, which do not plot, but give a list of values based on what metrics you want

**Comment by christianhidber** [comment]
could you make an example of what you would pass into agent.score and how the output would look like ?

**Comment by DJCordhose** [comment]
min, max, mean, all = agent.score(num_episodes=1000, metrics=['min', 'max', 'mean', 'list'])
min => 0.2
max => 0.8
mean => 0.7
all => [0.2, ....., 0.7]

**Comment by christianhidber** [comment]
ah I see. You could try this one (already supported):

import statistics
pc = agent.play(num_episodes=1000)
r = list(pc.sum_of_rewards.values())
min(r), max(r), statistics.mean(r), statistics.stdev(r), r

what do you think ?

**Comment by DJCordhose** [comment]
Looks great, I guess we could provide a convenience wrapper around that
code to provide people with an API they are familiar with.

**Comment by christianhidber** [comment]
what about a score() function on play_context yielding all available scores as a dictioinary?

agent.play(num_episodes=1000).score()

=> {'min':0.2, 'max': 0.8, 'mean':0.7,'std':0.1,'all'=[...]}

**Comment by DJCordhose** [comment]
Looks nice, but maybe an additional alias to a direct score method on the
agent to make the API most intuitive and easy for code competition.

on agent we would see
- train
- play and
- score

which would make it pretty obvious IMHO

**Comment by christianhidber** [comment]
good point. let's do that.

**Comment by DJCordhose** [comment]
I would be happy to take care of this, but it will take some time until I get to it.

**Comment by christianhidber** [comment]
thats great. no problem.

**Comment by DJCordhose** [comment]
implemented directly into main branch, as minimal implementation in abstract base class 'EasyAgent'
